[package]
name = "ant25"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "ant25"
path = "src/main.rs"

[lib]
name = "ant25lib"
path = "src/lib/lib.rs"
